### ISSUE TITLE
WebtorrentDownloader & Downloader not working when forked.

### ISSUE THREAD

**Issue by jczasgit** [jczasgit/synchronos#9]
**Error Stack**
```
DownloaderError [Downloader Error]: Error forking download.
    at Webtorrendownloader._fork (F:\projects\movify2\dist\core\Downloader.js:185:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  error: TypeError: Converting circular structure to JSON
      --> starting at object with constructor 'WebTorrent'
      |     property '_connPool' -> object with constructor 'ConnPool'
      --- property '_client' closes the circle
      at stringify (<anonymous>)
      at writeChannelMessage (node:internal/child_process/serialization:120:20)
      at ChildProcess.target._send (node:internal/child_process:822:17)
      at ChildProcess.target.send (node:internal/child_process:722:19)
      at Webtorrendownloader.fork (F:\projects\movify2\dist\core\ThreadManager.js:52:23)
      at Webtorrendownloader._fork (F:\projects\movify2\dist\core\Downloader.js:181:24)
      at Webtorrendownloader.start (F:\projects\movify2\dist\core\WebtorrentDownloader.js:93:34)
      at Webtorrendownloader.add (F:\projects\movify2\dist\core\WebtorrentDownloader.js:56:22)
      at Object.<anonymous> (F:\projects\movify2\dist\index.js:179:19)
      at Module._compile (node:internal/modules/cjs/loader:1092:14)
}
```

**Comment by jczasgit** [comment]
***Incorrect UTP binding***

Webtorrent library error.

***Error Stack***
`Error: invalid argument
    at Connection._connect (/mnt/sdb/backends/synchronos/node_modules/utp-native/lib/connection.js:197:11)
    at /mnt/sdb/backends/synchronos/node_modules/utp-native/lib/connection.js:189:10
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:63:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7) {
  code: 'EINVAL'
}`

**Comment by jczasgit** [comment]
Work around => enable asyncMode when initiating Downloader instance.

**Comment by jczasgit** [comment]
Related files:
- src/core/WebtorrentDownloader.ts
- src/core/Downloader.ts
- src/coreThreadManager.ts
- src/scripts/torrent.script.ts
